services:
  haha-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3090:3000"
    network_mode: host
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production